# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
