# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('classtest1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classtest2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('groupwork', models.DecimalField(decimal_places=2, max_digits=5)),
                ('projectwork', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total50', models.DecimalField(decimal_places=2, max_digits=5)),
                ('examsscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total100', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
    ]
