# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_grade_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='exams50',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
            preserve_default=False,
        ),
    ]
