# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_grade_exams50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exams50',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total50',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
