# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20170105_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total100', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quarter', models.CharField(max_length=10)),
                ('attendance', models.CharField(max_length=5)),
                ('outof', models.CharField(max_length=5)),
                ('comments_teacher', models.CharField(max_length=400)),
                ('comments_head', models.CharField(max_length=400)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
    ]
