# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_gradeall'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='sclass',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradeall',
            name='sclass',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
