# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_teachersubject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSubject',
            new_name='Teacher_Subject',
        ),
    ]
