# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20170109_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tclass', models.CharField(max_length=5)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher_Subject',
        ),
    ]
