# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20170109_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Class',
            new_name='TeacherClass',
        ),
    ]
